spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.86.34.238:3306/geography?useUnicode=true&characterEncoding=utf-8
    password: ttsuser
    username: HTDaBeJ81Nv2
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: /mapper/**.xml
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
